name: Deploy (Production Build)

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [eslint, stylelint]

    steps:
      - name: Dive into the repo
        uses: actions/checkout@v2
      - name: Deploy to vercel (preview build)
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: --prod
